### ISSUE TITLE
Update of the library?

### ISSUE THREAD

**Issue by NicolasLourenco** [AudioKit/MIDISequencer#12]
Hey, 
Can you update MidiSequencer in order to deal with `AKAppleSequencer` ?

Thanks you

**Comment by eljeff** [comment]
?

**Comment by NicolasLourenco** [comment]
This is not working anymore

**Comment by aure** [comment]
This seems to work for me, but Jeff is right that its based on stuff we are moving away from.

**Comment by aure** [comment]
I did just push the fix for 4.10.1
