### ISSUE TITLE
MIDISequencer is not a Swift Package

### ISSUE THREAD

**Issue by btfranklin** [AudioKit/MIDISequencer#16]
My project uses all the AudioKit stuff purely in the form of Swift Package Manager packages. I assume this project is where the stuff that used to have the names "Sequencer" and "SequencerTrack" in the core AudioKit package now lives...But if that's the case, I need this to be a Swift Package, as well.

**Comment by btfranklin** [comment]
Nevermind. Despite the name, it seems clear this isn't where that stuff lives. I'm not sure this is even still a "living" subproject.

**Comment by aure** [comment]
Yeah, if its not on AudioKit.io or suffixed with "AudioKit" it's not an "official" package. And you're right that its pretty much in disrepair.

**Comment by btfranklin** [comment]
It took me a little while to understand the new package breakout. I see now that the Sequencer stuff I needed was still in the main AudioKit package itself, but I needed to add an import for the AudioKitEX module. That was what was unclear.

**Comment by aure** [comment]
The website pages are generated from the /docs/ directory if you want to help the next guy out by updating the migration guide.
