### ISSUE TITLE
Xcode 9.3 & Cocoapods

### ISSUE THREAD

**Issue by nl** [AudioKit/MIDISequencer#9]
Hello,

currently, build is failing for the example apps. Easy to replicate: `pod try MIDISequencer` & build Mac example. Something about AudioKit being built with Swift 4.0.2. I had to downgrade to earlier Xcode/Swift versions to build.

**Comment by aure** [comment]
Yeah, this is going to be addressed with an update for Xcode 10, or maybe 11.  Closing since this is such an old issue.  Sorry that no one ever responded.
